Add unique question
satoshinbp/grabo pull request #57
Opened 2021-11-05 19:03 UTC by yoshiki1009

implement add and delete unique question feature

2021-11-07 03:41 UTC, satoshinbp requested changes
Use plural case for variable: array for better readability. 
Please resolve conflicts also.

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +  const [uniqQuestion, setUniqQuestion] = useState([''])
```suggestion
  const [uniqQuestions, setUniqQuestions] = useState([])
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +    setUniqQuestion('')
```suggestion
    setUniqQuestions([])
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +            {uniqQuestion.map((element, index) => (
```suggestion
            {uniqQuestions.map((uniqQuestion, index) => (
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +                  value={uniqQuestion[index]}
```suggestion
                  value={uniqQuestion}
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
>    const [highlitedQuestion, setHighlitedQuestion] = useState([])
```suggestion
  const [highlitedQuestions, setHighlitedQuestions] = useState([])
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
>        uniqQuestion: uniqQuestion,
```suggestion
      highlitedQuestions,
      uniqQuestions,
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +    setHighlitedQuestion([])
```suggestion
    setHighlitedQuestions([])
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +  }
```suggestion
  const handleChange = (i, text) => {
    const newUniqQuestions = [...uniqQuestions]
    newUniqQuestions[i] = text
    setUniqQuestions(newUniqQuestions)
  }
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +    setUniqQuestion([...uniqQuestion, ''])
```suggestion
    setUniqQuestions([...uniqQuestions, ''])
```

2021-11-07 03:41 UTC, satoshinbp commented on client/src/screens/CreateProduct.js
> +  }
```suggestion
  const removeFormFields = (i) => {
    const newUniqQuestions = [...uniqQuestions]
    newUniqQuestions.splice(i, 1)
    setUniqQuestions(newUniqQuestions)
  }
```

2021-11-07 03:41 UTC, satoshinbp commented on controllers/productController.js
> +        description: uniqquestion,
```suggestion
    uniqQandAs: req.body.uniqQuestions.map((uniqQuestion, index) => ({
      question: {
        description: uniqQuestion,
```

2021-11-07 22:56 UTC, yoshiki1009 commented
fixed variable naming and confliction

2021-11-08 00:34 UTC, satoshinbp approved these changes

2021-11-08 00:34 UTC, merged