Notification list
satoshinbp/grabo pull request #88
Opened 2021-11-20 22:26 UTC by yoshiki1009

create a basic notification function
when some user posts product that belongs to your group, a notification list is displayed on the notification screen.
You can go to the notification list from the top right bell icon.

issue: I am struggling with how to hide notification tab from the bottom tab bar, so I put it there temporarily. 
          When the user jumps to the product page from a notification list, sometimes it works, but sometimes it failed...

next:  The feature that once the user checked the notification, that list is removed from the lists is coming later

2021-11-20 23:26 UTC, satoshinbp requested changes
I understand that there will be only one screen for notification. In that case, we don't need stack navigator.

2021-11-20 23:26 UTC, satoshinbp commented on client/src/components/Header.js
> +            <Pressable onPress={() => navigation.navigate('NotificationTab', { screen: 'NotificationStacks' })}>
```suggestion
            <Pressable onPress={() => navigation.navigate('Notification')}>
```

2021-11-20 23:26 UTC, satoshinbp commented on client/src/navigators/NotificationStacks.js
> +}
Delete this file

2021-11-20 23:26 UTC, satoshinbp commented on client/src/navigators/Tabs.js
> +import NotificationStacks from './NotificationStacks'
```suggestion
```

2021-11-20 23:26 UTC, satoshinbp commented on client/src/navigators/Tabs.js
> +      <Tab.Screen name="NotificationTab" component={NotificationStacks} />
import Notification screen

```suggestion
      <Tab.Screen name="Notification" component={Notification} />
```

2021-11-20 23:26 UTC, satoshinbp commented on client/src/screens/Notification.js
> +  const onPress = (item) => navigation.navigate('MyProductsTab', { screen: 'MyProduct', params: { id: item._id } })
item._id is notidfication id, not product id. Need to store product id in notification object and pass it to navigate params

2021-11-21 21:03 UTC, yoshiki1009 commented
fix and refactored notification function

2021-11-22 16:25 UTC, satoshinbp approved these changes

2021-11-22 16:25 UTC, merged